workspace:
  base: /go
  path: src/github.com/astronomerio/astro-cli

pipeline:
  build:
    image: golang
    commands: 
      - make build
  
  test:
    image: golang
    commands:
      - make test

  push:
    image: golang
    commands: |
      if [ "${CI_TAG}" != "" ]; then
        curl -sL https://git.io/goreleaser | bash
      else
        echo "Not tagged, skipping step"
      fi
    when:
      tag: v*.*.*
