workspace:
  base: /go
  path: src/github.com/astronomerio/astro-cli

pipeline:
  build:
    image: golang
    commands: 
      - make build
  
  test:
    image: golang
    commands:
      - make test

  push:
    image: goreleaser/goreleaser:v0.86
    secrets: [ github_token ]
    commands:
      - git fetch --no-tags origin +refs/tags/${DRONE_TAG}:refs/tags/${DRONE_TAG}
      - goreleaser release --rm-dist
    when:
      event: tag
