defaults: &defaults
  working_directory: /go/src/github.com/astronomerio/astro-cli

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: "Astro version:"
          command: |
            echo $CIRCLE_TAG
  # deploy:
  #   <<: *defaults
  #   docker:
  #      - image: circleci/golang:1.8
  #   steps:
  #     - checkout
      # - run:
      #     name: "Install Goreleaser"
      #     command: |
      #       if [ "${CIRCLE_TAG}" != "" ]; then
      #         curl -sL https://git.io/goreleaser | bash
      #       else
      #         echo "Not tagged, skipping step"
      #       fi
workflows:
  version: 2
  distribute:
    jobs:
      - build:
          filters:
            branches:
              only: master
            tags:
              only: /^v\d[\d\.]+/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v\d[\d\.]+/
